version: '3.7'

services:

  app:
    container_name: fast-npm-search
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "VIRTUAL_HOST=api.fast-npm-search.xyz"
      - "VIRTUAL_PORT=3000"
    expose:
      - 3000